server:
  port: 9899
security:
  user:
    password: user  # 直接登录时的密码
  ignored: /
  sessions: never   # session策略
  oauth2:
    sso:
      loginPath: /login   # 登录路径
    client:
      clientId: f1ef8cfca31cb540b44e
      clientSecret: 9085dc0071320a9794fd42173c9cf8fa3f4af5aa
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
    resource:
      userInfoUri: https://api.github.com/user
      preferTokenInfo: false


spring:
  application:
    name: security-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/